### ISSUE TITLE
unselecting a sensor in a graph lets whole graph disappear

### ISSUE THREAD

**Issue by do3meli** [do3meli/piLogger-cloud#1]
when unselecting a sensor from a graph all other sensor disappear from the graph as well. when resizing the windwo the still selected graphs seems to be shown again.

**Comment by maglub** [comment]
Really weird.

I copied the code in your draw_charts() function into the piLogger js/myfunctions.js, replacing the (almost) identical code piece there. The blending out of data works, and there is no difference from the previous code.

https://github.com/maglub/piLogger/blob/master/html/js/myfunctions.js#L111
